# Generated by Django 2.0.2 on 2018-03-31 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_fresh_user', '0002_auto_20180326_1015'),
        ('daily_fresh_goods', '0002_auto_20180326_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_user.UserInfor')),
            ],
        ),
    ]
