# Generated by Django 2.0.2 on 2018-03-26 06:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_pic', models.URLField(null=True)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_unit', models.CharField(max_length=20)),
                ('goods_sales_num', models.IntegerField()),
                ('goods_stock', models.IntegerField()),
                ('goods_short_desc', models.CharField(max_length=200)),
                ('goods_detail', tinymce.models.HTMLField()),
                ('is_delete', models.BooleanField(default=False)),
                ('good_advance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type_name', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_goods.GoodsType'),
        ),
    ]
