# Generated by Django 2.0.2 on 2018-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_fresh_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
