# Generated by Django 2.0.2 on 2018-03-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=30)),
                ('user_receive_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=20)),
                ('user_zip_code', models.CharField(max_length=10)),
                ('user_mobile_phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
