# Generated by Django 2.0.2 on 2018-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_fresh_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='user_address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_mobile_phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_receive_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='user_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
