# Generated by Django 2.0.2 on 2018-03-31 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_fresh_goods', '0002_auto_20180326_1523'),
        ('daily_fresh_user', '0002_auto_20180326_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.TimeField(auto_now=True)),
                ('order_ispay', models.BooleanField(default=False)),
                ('order_total_num', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_user.UserInfor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_goods.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_fresh_order.Order')),
            ],
        ),
    ]
