# Generated by Django 2.0.2 on 2018-03-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_fresh_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_tyepe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.CharField(default='', max_length=120),
        ),
    ]
