# Generated by Django 2.0.2 on 2018-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_fresh_order', '0002_auto_20180331_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
